### ISSUE TITLE
Spinning fast a trackball/mouse gets stuck the player in the middle in games like Millipede.

### ISSUE THREAD

**Issue by fastpop72** [libretro/FBNeo#132]
Using games like Millipede with "Mouse (Ball only)" set and using a trackball (or a mouse) often the player get stuck in the middle of the screen spinning fast in a direction.
This does not occur in FBNeo standalone because setting an "Analog sensitivity" to 25% resolve the issue.
The "Analog speed" setting of the libretro core unfortunately doesn't help.

**Comment by barbudreadmon** [comment]
> setting an "Analog sensitivity" to 25% resolve the issue.

Needing such a low setting is unexpected, i guess i'll have to rework this core option (current min of the core option is equal to 37.5%)

**Comment by fastpop72** [comment]
The core option you mean is "Analog speed"? The one you can set from 1 to 10?

I think "speed" and "sensitivity" are different settings... anyway if you can set the minimum speed equal to 25% i'm happy to test...

**Comment by dinkc64** [comment]
the sens. setting I recently added simply controls the "analog  0x0100" value in the game's ini file.  
It can go from 0x40 to 0x400, I believe 25% in the UI is 0x40.  I might change it so that it can go lower, though!
p.s. really, I didn't create this silly percentage math, it's from the "adjust cpu speed" dialog - but it might be helpful if we both use the same math to calculate this.  It's in burner/win32/inpd.cpp, search for SliderInit() / SliderUpdate() / SliderExit()

best regards,
- dink

**Comment by barbudreadmon** [comment]
@fastpop72 internally that's the same variable (`nAnalogSpeed`), just different names and different values available.

@dinkc64 i'll change that stuff to a 5%-100% range with 5% steps

**Comment by barbudreadmon** [comment]
@fastpop72 should be fixed, could you test with the new core option ?

**Comment by fastpop72** [comment]
@barbudreadmon Sure but i won't test until saturday, i'm on a lil' vacation. Thanks.

**Comment by fastpop72** [comment]
@barbudreadmon I tested the Analog speed option in Millipede. Setting 25% works much better but the "stuck in the middle" issue is not resolved. I heard from @dinkc64 that in trackballs and mouse when you spin in a direction it gives the value from 00 to FF then when you go further the FF value it restarts from 00 and so on... maybe the core read the trackball value until FF then it stops reading until it receive a decremented value?

Here's a video of the issue:

https://youtu.be/hGwcGIXDDqM

**Comment by barbudreadmon** [comment]
> the core read the trackball value until FF then it stops reading until it receive a decremented value?

The core don't read trackball value directly, it reads the value the frontend (RA) is providing. 

I think i understand what's the issue here, but it's not a core issue : as soon as the mouse pointer is reaching the far left of my display, RA will stop providing "decrementing values".
Maybe it will be easier to explain it like this : let's say millipede's spaceship is in the middle of the game screen, but the actual mouse pointer is at the far left of RA's viewport (or beyond), you won't be able to go left in the game screen because RA is limited by its viewport. Basically RA only detects mouse movements over its viewport.

Well, that's definitely not something i can solve at the core level, you'll have to open an issue in the RA repo about this.

**Comment by dinkc64** [comment]
that's unfortunate :(

**Comment by dinkc64** [comment]
@barbudreadmon please see forum for an important request for help :)  (sorry for posting here)
