### ISSUE TITLE
Pacman 25th Anniversary - Galaga Highscore Screen Bug (25pacmano)

### ISSUE THREAD

**Issue by RandyRVA** [libretro/FBNeo#527]
Once you've completed entering your initials at the Galaga high score screen, the emulation speed drops dramatically.  The high score music slows to a "note" by "note" snails pace and no buttons work until the music is done playing.  This has been verified on a PC and Raspberry Pi 2 both using Retroarch and a freshly compiled lr-fbneo.

**Comment by dinkc64** [comment]
Hi, thanks for the bug report, the issue has been resolved.

best regards,
- dink

**Comment by RandyRVA** [comment]
Excellent!  When will the updated build be available?

**Comment by barbudreadmon** [comment]
i just merged the fix into the libretro port

**Comment by RandyRVA** [comment]
This issue seems to still exist.  I updatied through Retropie lr-fbneo update from source.  I'm pretty sure it's coming from a good source: gitPullOrClone "$md_build" https://github.com/libretro/FBNeo.git

Thanks for all the hard work you guys put into this project, it's greatly appreciated!

**Comment by RandyRVA** [comment]
This issue seems to still exist. I updatied through Retropie lr-fbneo update from source. I'm pretty sure it's coming from a good source: gitPullOrClone "$md_build" https://github.com/libretro/FBNeo.git

Thanks for all the hard work you guys put into this project, it's greatly appreciated!

**Comment by barbudreadmon** [comment]
@dinkc64 i confirm i still have the issue too (on x86)

**Comment by barbudreadmon** [comment]
@RandyRVA we won't fix this bug, it would require too much work (full rewrite of our z180 cpu core) for games that already have perfect emulation separately, please use galaga and pacman instead.

**Comment by RandyRVA** [comment]
Totally understand guys!  Thanks for looking at it.

**Comment by dinkc64** [comment]
sorry for the false alarm 2 days ago!  I think the heat must have been getting to me...

**Comment by RandyRVA** [comment]
No worries man!  I know what you mean about the heat, it's brutal!  I'm just thankful that you guys are even doing emulators.  I was planning on having a single machine that booted into this particular rom because it contained the three favorites in my household and I didn't want to deal with any kind of frontend menu.  I guess I will just need to make sure nobody can touch my Galaga highscore!  Lol.  Thanks for all the effort on this project!  fb-neo is really amazing!

**Comment by dinkc64** [comment]
Since I like what you're trying to do I decided to put some elbow grease into this one.  It took 5 1/2 hours, but, this game set is now fully working without slowdown.  The fix should be available sometime today or tomorrow.

So the deal is: if I'm ever on your side of town, you'll have to let me play a game on your machine :)

best regards,
- dink

**Comment by RandyRVA** [comment]
Wow!  That's really nice of you!  My wife and the kids will be so happy about this one!  Really, it's the only time we want on the machine!  You must be a family guy too!  Hey, if you are ever in Richmond, Virginia, you are welcome anytime.  We'd love to have you!  You are a really good person, thank you so much for your time and advanced programming skills!  Have a great weekend my friend!

**Comment by dinkc64** [comment]
Sounds like a deal, I'll let you know next time I'm out that way - in Michigan right now :)  

Me or barbudreadmon will let you know as soon as the fix makes its way into libretro.

best regards,
- dink

**Comment by barbudreadmon** [comment]
The fix is on git !

**Comment by RandyRVA** [comment]
Thanks again for your hard work guys and see ya soon C64!
