### ISSUE TITLE
Hiscores not loading in some games

### ISSUE THREAD

**Issue by eadmaster** [libretro/FBNeo#702]
One of these games is `mysticri`.

I've found this is due to [this check that rely on the game driver to specify if the hiscore is supported or not](https://github.com/libretro/FBNeo/blob/master/src/burn/hiscore.cpp#L155).

Since new games are added constantly to the [MAME datfile](https://github.com/mamedev/mame/blob/master/plugins/hiscore/hiscore.dat) maybe it is better to disable the check?

**Comment by eadmaster** [comment]
Another issue is [this hard limit for the ranges](https://github.com/libretro/FBNeo/blob/master/src/burn/hiscore.cpp#L8).

There a few games in the current datfile with more than 20 ranges associated: `boblbobl`, `bublboblp`, [`cosmicg`](https://github.com/mamedev/mame/blob/master/plugins/hiscore/hiscore.dat#L2894).

**Comment by barbudreadmon** [comment]
duplicate of https://github.com/finalburnneo/FBNeo/issues/378

**Comment by barbudreadmon** [comment]
yes

**Comment by eadmaster** [comment]
Fixed in my libretro-only branch by calling `HiscoreReset()` in `retro_reset()`.
I'll monitor the other issue for a better solution.

**Comment by barbudreadmon** [comment]
well, no, you didn't fix anything, you should read the other issue...

**Comment by eadmaster** [comment]
I've just tried resetting the libretro core with an hiscore loaded multiple times, and my `.hi` file stayed intact, so i guess this fixes the problem with the libretro port, at least...

**Comment by barbudreadmon** [comment]
As mentioned in the other issue, games can decide to reset themselves internally for various reasons, what you fixed is only manual reset. That's not a fix, that's only a dirty hack.

**Comment by eadmaster** [comment]
Ok, i see your point now. I'm thinking another solution now i'll post in https://github.com/finalburnneo/FBNeo/issues/378 after studying the code a bit more...

**Comment by dinkc64** [comment]
dinkfucious say:
"It's best not to try to short-cut things, and do them the right way."
